import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Player from '../models/Player.js';

dotenv.config();

const legends = [
  // ===================== GOALKEEPERS (15) =====================
  { name: 'Gianluigi Buffon', nickname: 'Superman', country: 'Italy', position: 'Goalkeeper', secondaryPositions: [], preferredFoot: 'Right', overall: 93, basePrice: 25000000, ageAtRetirement: 45, height: '192 cm', weight: '92 kg', peakClub: 'Juventus', careerYears: '1995-2023', jerseyNumber: 1, captain: true, worldCupWinner: true, ballonDor: 0, championsLeague: 0, leagueTitles: 10, internationalCaps: 176, internationalGoals: 0, description: 'One of the greatest goalkeepers of all time, known for his incredible longevity and leadership.', rarity: 'Mythic' },
  { name: 'Iker Casillas', nickname: 'San Iker', country: 'Spain', position: 'Goalkeeper', secondaryPositions: [], preferredFoot: 'Left', overall: 92, basePrice: 22000000, ageAtRetirement: 39, height: '185 cm', weight: '85 kg', peakClub: 'Real Madrid', careerYears: '1999-2020', jerseyNumber: 1, captain: true, worldCupWinner: true, ballonDor: 0, championsLeague: 3, leagueTitles: 5, internationalCaps: 167, internationalGoals: 0, description: 'Legendary Spanish goalkeeper who won everything with club and country.', rarity: 'Mythic' },
  { name: 'Manuel Neuer', nickname: 'Sweeper Keeper', country: 'Germany', position: 'Goalkeeper', secondaryPositions: [], preferredFoot: 'Right', overall: 94, basePrice: 35000000, ageAtRetirement: 38, height: '193 cm', weight: '92 kg', peakClub: 'Bayern Munich', careerYears: '2006-2025', jerseyNumber: 1, captain: true, worldCupWinner: true, ballonDor: 0, championsLeague: 2, leagueTitles: 11, internationalCaps: 117, internationalGoals: 0, description: 'Revolutionized the goalkeeper position with his sweeper-keeper style.', rarity: 'Mythic' },
  { name: 'Peter Schmeichel', nickname: 'The Great Dane', country: 'Denmark', position: 'Goalkeeper', secondaryPositions: [], preferredFoot: 'Right', overall: 91, basePrice: 20000000, ageAtRetirement: 38, height: '193 cm', weight: '95 kg', peakClub: 'Manchester United', careerYears: '1981-2003', jerseyNumber: 1, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 5, internationalCaps: 129, internationalGoals: 1, description: 'The original Premier League great goalkeeper, known for his massive presence.', rarity: 'Legend' },
  { name: 'Oliver Kahn', nickname: 'Der Titan', country: 'Germany', position: 'Goalkeeper', secondaryPositions: [], preferredFoot: 'Right', overall: 92, basePrice: 20000000, ageAtRetirement: 39, height: '188 cm', weight: '90 kg', peakClub: 'Bayern Munich', careerYears: '1987-2008', jerseyNumber: 1, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 8, internationalCaps: 86, internationalGoals: 0, description: 'Intimidating German goalkeeper known for his aggressive style and leadership.', rarity: 'Legend' },
  { name: 'Petr Čech', nickname: 'The Wall', country: 'Czech Republic', position: 'Goalkeeper', secondaryPositions: [], preferredFoot: 'Left', overall: 90, basePrice: 18000000, ageAtRetirement: 37, height: '196 cm', weight: '90 kg', peakClub: 'Chelsea', careerYears: '1999-2019', jerseyNumber: 1, captain: false, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 4, internationalCaps: 124, internationalGoals: 0, description: 'One of the most reliable keepers in Premier League history.', rarity: 'Legend' },
  { name: 'Edwin van der Sar', nickname: 'The Iceman', country: 'Netherlands', position: 'Goalkeeper', secondaryPositions: [], preferredFoot: 'Right', overall: 89, basePrice: 16000000, ageAtRetirement: 40, height: '197 cm', weight: '85 kg', peakClub: 'Manchester United', careerYears: '1990-2011', jerseyNumber: 1, captain: false, worldCupWinner: false, ballonDor: 0, championsLeague: 2, leagueTitles: 6, internationalCaps: 130, internationalGoals: 0, description: 'Dutch legend who held the record for longest clean sheet streak.', rarity: 'Legend' },
  { name: 'Dino Zoff', nickname: 'Nonno', country: 'Italy', position: 'Goalkeeper', secondaryPositions: [], preferredFoot: 'Right', overall: 91, basePrice: 18000000, ageAtRetirement: 41, height: '182 cm', weight: '80 kg', peakClub: 'Juventus', careerYears: '1961-1983', jerseyNumber: 1, captain: true, worldCupWinner: true, ballonDor: 0, championsLeague: 0, leagueTitles: 6, internationalCaps: 112, internationalGoals: 0, description: 'World Cup winning captain at age 40, the oldest World Cup winner.', rarity: 'Legend' },
  { name: 'Walter Zenga', nickname: 'L\'Uomo Ragno', country: 'Italy', position: 'Goalkeeper', secondaryPositions: [], preferredFoot: 'Right', overall: 87, basePrice: 10000000, ageAtRetirement: 38, height: '188 cm', weight: '85 kg', peakClub: 'Inter Milan', careerYears: '1978-1999', jerseyNumber: 1, captain: false, worldCupWinner: false, ballonDor: 0, championsLeague: 0, leagueTitles: 1, internationalCaps: 58, internationalGoals: 0, description: 'Held the record for longest streak without conceding in Serie A.', rarity: 'Icon' },
  { name: 'José Luis Chilavert', nickname: 'Chila', country: 'Paraguay', position: 'Goalkeeper', secondaryPositions: [], preferredFoot: 'Left', overall: 86, basePrice: 10000000, ageAtRetirement: 38, height: '188 cm', weight: '88 kg', peakClub: 'Vélez Sarsfield', careerYears: '1982-2004', jerseyNumber: 1, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 0, leagueTitles: 4, internationalCaps: 74, internationalGoals: 8, description: 'Famous goalscoring goalkeeper who took free kicks and penalties.', rarity: 'Icon' },
  { name: 'David Seaman', nickname: 'Safe Hands', country: 'England', position: 'Goalkeeper', secondaryPositions: [], preferredFoot: 'Right', overall: 87, basePrice: 12000000, ageAtRetirement: 41, height: '193 cm', weight: '90 kg', peakClub: 'Arsenal', careerYears: '1981-2004', jerseyNumber: 1, captain: false, worldCupWinner: false, ballonDor: 0, championsLeague: 0, leagueTitles: 2, internationalCaps: 75, internationalGoals: 0, description: 'England\'s number one for a decade. Arsenal legend.', rarity: 'Icon' },
  { name: 'Rogério Ceni', nickname: 'Mito', country: 'Brazil', position: 'Goalkeeper', secondaryPositions: [], preferredFoot: 'Right', overall: 85, basePrice: 8000000, ageAtRetirement: 42, height: '188 cm', weight: '85 kg', peakClub: 'São Paulo', careerYears: '1990-2015', jerseyNumber: 1, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 0, leagueTitles: 3, internationalCaps: 16, internationalGoals: 0, description: 'Highest scoring goalkeeper in history with over 100 career goals.', rarity: 'Icon' },
  { name: 'Cláudio Taffarel', nickname: 'Taffa', country: 'Brazil', position: 'Goalkeeper', secondaryPositions: [], preferredFoot: 'Right', overall: 86, basePrice: 10000000, ageAtRetirement: 37, height: '182 cm', weight: '78 kg', peakClub: 'Brazil', careerYears: '1985-2003', jerseyNumber: 1, captain: false, worldCupWinner: true, ballonDor: 0, championsLeague: 0, leagueTitles: 2, internationalCaps: 101, internationalGoals: 0, description: 'Brazil\'s World Cup winning goalkeeper in 1994 and 2002 runner-up.', rarity: 'Icon' },
  { name: 'Jens Lehmann', nickname: 'Mad Jens', country: 'Germany', position: 'Goalkeeper', secondaryPositions: [], preferredFoot: 'Right', overall: 87, basePrice: 12000000, ageAtRetirement: 39, height: '190 cm', weight: '87 kg', peakClub: 'Arsenal', careerYears: '1989-2011', jerseyNumber: 1, captain: false, worldCupWinner: false, ballonDor: 0, championsLeague: 0, leagueTitles: 1, internationalCaps: 61, internationalGoals: 0, description: 'Key member of Arsenal\'s Invincibles and German national team.', rarity: 'Icon' },
  { name: 'Víctor Valdés', nickname: 'Valdés', country: 'Spain', position: 'Goalkeeper', secondaryPositions: [], preferredFoot: 'Right', overall: 86, basePrice: 12000000, ageAtRetirement: 35, height: '183 cm', weight: '78 kg', peakClub: 'Barcelona', careerYears: '2002-2017', jerseyNumber: 1, captain: false, worldCupWinner: false, ballonDor: 0, championsLeague: 3, leagueTitles: 6, internationalCaps: 20, internationalGoals: 0, description: 'Barcelona\'s number one during their golden era. Zamora Trophy winner.', rarity: 'Icon' },

  // ===================== DEFENDERS (30) =====================
  { name: 'Paolo Maldini', nickname: 'Il Capitano', country: 'Italy', position: 'Defender', secondaryPositions: ['Left Back'], preferredFoot: 'Left', overall: 95, basePrice: 35000000, ageAtRetirement: 41, height: '186 cm', weight: '85 kg', peakClub: 'AC Milan', careerYears: '1984-2009', jerseyNumber: 3, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 5, leagueTitles: 7, internationalCaps: 126, internationalGoals: 7, description: 'One of the greatest defenders in history. Spent entire career at AC Milan.', rarity: 'Mythic' },
  { name: 'Franz Beckenbauer', nickname: 'Der Kaiser', country: 'Germany', position: 'Defender', secondaryPositions: ['Midfielder'], preferredFoot: 'Right', overall: 96, basePrice: 45000000, ageAtRetirement: 37, height: '181 cm', weight: '75 kg', peakClub: 'Bayern Munich', careerYears: '1964-1983', jerseyNumber: 5, captain: true, worldCupWinner: true, ballonDor: 2, championsLeague: 3, leagueTitles: 5, internationalCaps: 103, internationalGoals: 14, description: 'Invented the sweeper position. Won World Cup as player and manager.', rarity: 'Ultimate Legend' },
  { name: 'Fabio Cannavaro', nickname: 'Il Muro', country: 'Italy', position: 'Defender', secondaryPositions: [], preferredFoot: 'Right', overall: 92, basePrice: 30000000, ageAtRetirement: 37, height: '176 cm', weight: '75 kg', peakClub: 'Real Madrid', careerYears: '1992-2011', jerseyNumber: 23, captain: true, worldCupWinner: true, ballonDor: 1, championsLeague: 0, leagueTitles: 5, internationalCaps: 136, internationalGoals: 2, description: 'Only defender to win Ballon d\'Or in the 21st century. World Cup winning captain.', rarity: 'Mythic' },
  { name: 'Sergio Ramos', nickname: 'El Camaron', country: 'Spain', position: 'Defender', secondaryPositions: ['Right Back'], preferredFoot: 'Right', overall: 92, basePrice: 30000000, ageAtRetirement: 38, height: '184 cm', weight: '82 kg', peakClub: 'Real Madrid', careerYears: '2004-2024', jerseyNumber: 4, captain: true, worldCupWinner: true, ballonDor: 0, championsLeague: 4, leagueTitles: 6, internationalCaps: 180, internationalGoals: 23, description: 'Legendary defender known for his goalscoring and last-minute heroics.', rarity: 'Legend' },
  { name: 'Carles Puyol', nickname: 'Puyi', country: 'Spain', position: 'Defender', secondaryPositions: ['Right Back'], preferredFoot: 'Right', overall: 91, basePrice: 28000000, ageAtRetirement: 36, height: '178 cm', weight: '80 kg', peakClub: 'Barcelona', careerYears: '1999-2014', jerseyNumber: 5, captain: true, worldCupWinner: true, ballonDor: 0, championsLeague: 3, leagueTitles: 6, internationalCaps: 100, internationalGoals: 3, description: 'Symbol of Barcelona\'s golden era. Known for his fierce defending and iconic hair.', rarity: 'Legend' },
  { name: 'Alessandro Nesta', nickname: 'Il Gladiatore', country: 'Italy', position: 'Defender', secondaryPositions: [], preferredFoot: 'Right', overall: 93, basePrice: 32000000, ageAtRetirement: 38, height: '187 cm', weight: '85 kg', peakClub: 'AC Milan', careerYears: '1993-2014', jerseyNumber: 13, captain: false, worldCupWinner: true, ballonDor: 0, championsLeague: 2, leagueTitles: 3, internationalCaps: 78, internationalGoals: 0, description: 'Elegant and technically perfect defender. Considered one of the best ever.', rarity: 'Mythic' },
  { name: 'Franco Baresi', nickname: 'Piscinin', country: 'Italy', position: 'Defender', secondaryPositions: [], preferredFoot: 'Right', overall: 93, basePrice: 30000000, ageAtRetirement: 38, height: '176 cm', weight: '74 kg', peakClub: 'AC Milan', careerYears: '1977-1997', jerseyNumber: 6, captain: true, worldCupWinner: true, ballonDor: 0, championsLeague: 3, leagueTitles: 6, internationalCaps: 81, internationalGoals: 1, description: 'The heart of Milan\'s legendary defense. Sweeper extraordinaire.', rarity: 'Mythic' },
  { name: 'Roberto Carlos', nickname: 'El Hombre Bala', country: 'Brazil', position: 'Defender', secondaryPositions: ['Left Midfielder'], preferredFoot: 'Left', overall: 91, basePrice: 32000000, ageAtRetirement: 38, height: '168 cm', weight: '70 kg', peakClub: 'Real Madrid', careerYears: '1991-2012', jerseyNumber: 3, captain: false, worldCupWinner: true, ballonDor: 0, championsLeague: 3, leagueTitles: 4, internationalCaps: 125, internationalGoals: 11, description: 'Legendary left back known for his powerful free kicks and attacking runs.', rarity: 'Mythic' },
  { name: 'Cafu', nickname: 'Il Pendolino', country: 'Brazil', position: 'Defender', secondaryPositions: ['Right Midfielder'], preferredFoot: 'Right', overall: 90, basePrice: 28000000, ageAtRetirement: 38, height: '176 cm', weight: '75 kg', peakClub: 'AC Milan', careerYears: '1989-2008', jerseyNumber: 2, captain: true, worldCupWinner: true, ballonDor: 0, championsLeague: 1, leagueTitles: 3, internationalCaps: 142, internationalGoals: 5, description: 'Only player to appear in three consecutive World Cup finals. Won two.', rarity: 'Legend' },
  { name: 'Javier Zanetti', nickname: 'Il Capitano', country: 'Argentina', position: 'Defender', secondaryPositions: ['Midfielder'], preferredFoot: 'Right', overall: 89, basePrice: 26000000, ageAtRetirement: 40, height: '178 cm', weight: '75 kg', peakClub: 'Inter Milan', careerYears: '1992-2014', jerseyNumber: 4, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 5, internationalCaps: 145, internationalGoals: 5, description: 'Mr. Inter. Played over 850 matches for the club. Model of consistency.', rarity: 'Legend' },
  { name: 'Dani Alves', nickname: 'Dani', country: 'Brazil', position: 'Defender', secondaryPositions: ['Right Midfielder'], preferredFoot: 'Right', overall: 89, basePrice: 25000000, ageAtRetirement: 40, height: '172 cm', weight: '72 kg', peakClub: 'Barcelona', careerYears: '2001-2023', jerseyNumber: 2, captain: false, worldCupWinner: false, ballonDor: 0, championsLeague: 3, leagueTitles: 7, internationalCaps: 126, internationalGoals: 8, description: 'Most decorated player in football history. Attacking full-back extraordinaire.', rarity: 'Legend' },
  { name: 'Philipp Lahm', nickname: 'The Magic Dwarf', country: 'Germany', position: 'Defender', secondaryPositions: ['Midfielder'], preferredFoot: 'Right', overall: 91, basePrice: 28000000, ageAtRetirement: 34, height: '170 cm', weight: '66 kg', peakClub: 'Bayern Munich', careerYears: '2002-2017', jerseyNumber: 21, captain: true, worldCupWinner: true, ballonDor: 0, championsLeague: 1, leagueTitles: 8, internationalCaps: 113, internationalGoals: 5, description: 'One of the most intelligent defenders. Could play both full-back positions.', rarity: 'Legend' },
  { name: 'Ashley Cole', nickname: 'Coley', country: 'England', position: 'Defender', secondaryPositions: ['Left Midfielder'], preferredFoot: 'Left', overall: 89, basePrice: 24000000, ageAtRetirement: 38, height: '176 cm', weight: '67 kg', peakClub: 'Chelsea', careerYears: '1999-2019', jerseyNumber: 3, captain: false, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 3, internationalCaps: 107, internationalGoals: 0, description: 'Considered by many as the best left-back of his generation.', rarity: 'Legend' },
  { name: 'Marcelo', nickname: 'Flo', country: 'Brazil', position: 'Defender', secondaryPositions: ['Left Midfielder'], preferredFoot: 'Left', overall: 88, basePrice: 22000000, ageAtRetirement: 35, height: '174 cm', weight: '72 kg', peakClub: 'Real Madrid', careerYears: '2005-2023', jerseyNumber: 12, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 5, leagueTitles: 6, internationalCaps: 58, internationalGoals: 6, description: 'One of the most skillful attacking left-backs in football history.', rarity: 'Legend' },
  { name: 'Jaap Stam', nickname: 'The Dutch Destroyer', country: 'Netherlands', position: 'Defender', secondaryPositions: ['Right Back'], preferredFoot: 'Right', overall: 90, basePrice: 26000000, ageAtRetirement: 35, height: '191 cm', weight: '92 kg', peakClub: 'Manchester United', careerYears: '1992-2007', jerseyNumber: 6, captain: false, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 4, internationalCaps: 67, internationalGoals: 3, description: 'Imposing center-back who dominated attackers with his strength.', rarity: 'Legend' },
  { name: 'Rio Ferdinand', nickname: 'Rio', country: 'England', position: 'Defender', secondaryPositions: [], preferredFoot: 'Right', overall: 90, basePrice: 28000000, ageAtRetirement: 37, height: '189 cm', weight: '85 kg', peakClub: 'Manchester United', careerYears: '1995-2015', jerseyNumber: 5, captain: false, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 6, internationalCaps: 81, internationalGoals: 3, description: 'Elegant ball-playing defender who redefined the position in England.', rarity: 'Legend' },
  { name: 'Nemanja Vidić', nickname: 'Vida', country: 'Serbia', position: 'Defender', secondaryPositions: [], preferredFoot: 'Right', overall: 90, basePrice: 26000000, ageAtRetirement: 34, height: '188 cm', weight: '86 kg', peakClub: 'Manchester United', careerYears: '2000-2016', jerseyNumber: 15, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 5, internationalCaps: 56, internationalGoals: 2, description: 'Fierce, no-nonsense defender. Premier League legend.', rarity: 'Legend' },
  { name: 'Marcel Desailly', nickname: 'The Rock', country: 'France', position: 'Defender', secondaryPositions: ['Midfielder'], preferredFoot: 'Right', overall: 89, basePrice: 20000000, ageAtRetirement: 35, height: '183 cm', weight: '82 kg', peakClub: 'Chelsea', careerYears: '1986-2004', jerseyNumber: 6, captain: true, worldCupWinner: true, ballonDor: 0, championsLeague: 2, leagueTitles: 3, internationalCaps: 116, internationalGoals: 3, description: 'Powerful center-back who won World Cup and European Championship.', rarity: 'Legend' },
  { name: 'John Terry', nickname: 'JT', country: 'England', position: 'Defender', secondaryPositions: [], preferredFoot: 'Right', overall: 90, basePrice: 26000000, ageAtRetirement: 37, height: '187 cm', weight: '85 kg', peakClub: 'Chelsea', careerYears: '1998-2018', jerseyNumber: 26, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 5, internationalCaps: 78, internationalGoals: 6, description: 'The heart of Chelsea\'s defense. One of the Premier League\'s greatest defenders.', rarity: 'Legend' },
  { name: 'Giorgio Chiellini', nickname: 'King Giorgio', country: 'Italy', position: 'Defender', secondaryPositions: ['Left Back'], preferredFoot: 'Left', overall: 90, basePrice: 24000000, ageAtRetirement: 39, height: '187 cm', weight: '85 kg', peakClub: 'Juventus', careerYears: '2000-2024', jerseyNumber: 3, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 0, leagueTitles: 9, internationalCaps: 117, internationalGoals: 8, description: 'Italian defensive titan known for his toughness and leadership.', rarity: 'Legend' },
  { name: 'Gerard Piqué', nickname: 'Piquenbauer', country: 'Spain', position: 'Defender', secondaryPositions: [], preferredFoot: 'Right', overall: 89, basePrice: 22000000, ageAtRetirement: 35, height: '194 cm', weight: '85 kg', peakClub: 'Barcelona', careerYears: '2004-2022', jerseyNumber: 3, captain: false, worldCupWinner: true, ballonDor: 0, championsLeague: 4, leagueTitles: 9, internationalCaps: 102, internationalGoals: 5, description: 'Elegant center-back who formed the core of Barcelona\'s golden era.', rarity: 'Legend' },
  { name: 'Ronald Koeman', nickname: 'Koeman', country: 'Netherlands', position: 'Defender', secondaryPositions: ['Midfielder'], preferredFoot: 'Right', overall: 88, basePrice: 18000000, ageAtRetirement: 34, height: '181 cm', weight: '81 kg', peakClub: 'Barcelona', careerYears: '1980-1997', jerseyNumber: 4, captain: false, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 5, internationalCaps: 78, internationalGoals: 14, description: 'Highest scoring defender in history, famous for his powerful free kicks.', rarity: 'Legend' },
  { name: 'Lúcio', nickname: 'Lúcio', country: 'Brazil', position: 'Defender', secondaryPositions: [], preferredFoot: 'Right', overall: 87, basePrice: 16000000, ageAtRetirement: 36, height: '188 cm', weight: '85 kg', peakClub: 'Inter Milan', careerYears: '1997-2013', jerseyNumber: 3, captain: false, worldCupWinner: true, ballonDor: 0, championsLeague: 1, leagueTitles: 4, internationalCaps: 105, internationalGoals: 4, description: 'World Cup winning Brazilian defender with a commanding presence.', rarity: 'Legend' },
  { name: 'Lilian Thuram', nickname: 'Thuuu', country: 'France', position: 'Defender', secondaryPositions: ['Right Back'], preferredFoot: 'Right', overall: 90, basePrice: 25000000, ageAtRetirement: 36, height: '185 cm', weight: '83 kg', peakClub: 'Juventus', careerYears: '1990-2008', jerseyNumber: 15, captain: false, worldCupWinner: true, ballonDor: 0, championsLeague: 0, leagueTitles: 3, internationalCaps: 142, internationalGoals: 2, description: 'Versatile defender who played both CB and RB at world class level.', rarity: 'Legend' },
  { name: 'Patrice Evra', nickname: 'Evra', country: 'France', position: 'Defender', secondaryPositions: [], preferredFoot: 'Left', overall: 87, basePrice: 18000000, ageAtRetirement: 38, height: '173 cm', weight: '74 kg', peakClub: 'Manchester United', careerYears: '1998-2019', jerseyNumber: 3, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 5, internationalCaps: 81, internationalGoals: 0, description: 'Dynamic left-back who was a key part of Manchester United\'s success.', rarity: 'Icon' },
  { name: 'Ricardo Carvalho', nickname: 'Carvalho', country: 'Portugal', position: 'Defender', secondaryPositions: [], preferredFoot: 'Right', overall: 88, basePrice: 18000000, ageAtRetirement: 38, height: '183 cm', weight: '79 kg', peakClub: 'Chelsea', careerYears: '1997-2017', jerseyNumber: 6, captain: false, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 4, internationalCaps: 89, internationalGoals: 6, description: 'Elegant Portuguese defender. Euro champion with Portugal.', rarity: 'Icon' },
  { name: 'Daniel Passarella', nickname: 'El Gran Capitán', country: 'Argentina', position: 'Defender', secondaryPositions: [], preferredFoot: 'Right', overall: 89, basePrice: 18000000, ageAtRetirement: 37, height: '173 cm', weight: '69 kg', peakClub: 'River Plate', careerYears: '1973-1989', jerseyNumber: 6, captain: true, worldCupWinner: true, ballonDor: 0, championsLeague: 0, leagueTitles: 5, internationalCaps: 70, internationalGoals: 22, description: 'Argentina\'s World Cup winning captain. Highest scoring defender in history.', rarity: 'Legend' },
  { name: 'Laurent Blanc', nickname: 'Le President', country: 'France', position: 'Defender', secondaryPositions: ['Midfielder'], preferredFoot: 'Right', overall: 88, basePrice: 18000000, ageAtRetirement: 37, height: '192 cm', weight: '86 kg', peakClub: 'Barcelona', careerYears: '1986-2003', jerseyNumber: 5, captain: false, worldCupWinner: true, ballonDor: 0, championsLeague: 1, leagueTitles: 3, internationalCaps: 97, internationalGoals: 16, description: 'Ball-playing defender known for his composure and leadership.', rarity: 'Legend' },
  { name: 'Giacinto Facchetti', nickname: 'Facchetti', country: 'Italy', position: 'Defender', secondaryPositions: ['Left Back'], preferredFoot: 'Left', overall: 89, basePrice: 20000000, ageAtRetirement: 36, height: '188 cm', weight: '80 kg', peakClub: 'Inter Milan', careerYears: '1960-1978', jerseyNumber: 3, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 2, leagueTitles: 4, internationalCaps: 94, internationalGoals: 3, description: 'Pioneered the attacking full-back role. Inter and Italy legend.', rarity: 'Legend' },
  { name: 'Maicon', nickname: 'Maicon', country: 'Brazil', position: 'Defender', secondaryPositions: ['Right Midfielder'], preferredFoot: 'Right', overall: 86, basePrice: 14000000, ageAtRetirement: 37, height: '186 cm', weight: '80 kg', peakClub: 'Inter Milan', careerYears: '2001-2021', jerseyNumber: 13, captain: false, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 5, internationalCaps: 76, internationalGoals: 7, description: 'Brazilian right-back known for his powerful runs and 2010 World Cup goal vs Korea.', rarity: 'Icon' },

  // ===================== MIDFIELDERS (36) =====================
  { name: 'Zinedine Zidane', nickname: 'Zizou', country: 'France', position: 'Midfielder', secondaryPositions: ['Forward'], preferredFoot: 'Right', overall: 96, basePrice: 50000000, ageAtRetirement: 34, height: '185 cm', weight: '80 kg', peakClub: 'Real Madrid', careerYears: '1988-2006', jerseyNumber: 10, captain: true, worldCupWinner: true, ballonDor: 1, championsLeague: 1, leagueTitles: 4, internationalCaps: 108, internationalGoals: 31, description: 'One of the greatest players of all time. Elegance personified.', rarity: 'Ultimate Legend' },
  { name: 'Andrés Iniesta', nickname: 'Don Andrés', country: 'Spain', position: 'Midfielder', secondaryPositions: ['Forward'], preferredFoot: 'Right', overall: 93, basePrice: 36000000, ageAtRetirement: 38, height: '171 cm', weight: '68 kg', peakClub: 'Barcelona', careerYears: '2002-2024', jerseyNumber: 8, captain: true, worldCupWinner: true, ballonDor: 0, championsLeague: 4, leagueTitles: 9, internationalCaps: 131, internationalGoals: 13, description: 'Scorer of the winning goal in the 2010 World Cup final. Football artist.', rarity: 'Mythic' },
  { name: 'Xavi', nickname: 'El Maestro', country: 'Spain', position: 'Midfielder', secondaryPositions: [], preferredFoot: 'Right', overall: 94, basePrice: 38000000, ageAtRetirement: 39, height: '170 cm', weight: '68 kg', peakClub: 'Barcelona', careerYears: '1998-2019', jerseyNumber: 6, captain: true, worldCupWinner: true, ballonDor: 0, championsLeague: 4, leagueTitles: 8, internationalCaps: 133, internationalGoals: 13, description: 'The metronome of Barcelona and Spain\'s tiki-taka domination.', rarity: 'Mythic' },
  { name: 'Luka Modrić', nickname: 'Lukita', country: 'Croatia', position: 'Midfielder', secondaryPositions: [], preferredFoot: 'Right', overall: 92, basePrice: 34000000, ageAtRetirement: 38, height: '172 cm', weight: '66 kg', peakClub: 'Real Madrid', careerYears: '2003-2025', jerseyNumber: 10, captain: true, worldCupWinner: false, ballonDor: 1, championsLeague: 6, leagueTitles: 4, internationalCaps: 178, internationalGoals: 26, description: 'Ballon d\'Or winner who ended the Messi-Ronaldo duopoly.', rarity: 'Mythic' },
  { name: 'Andrea Pirlo', nickname: 'Il Maestro', country: 'Italy', position: 'Midfielder', secondaryPositions: [], preferredFoot: 'Right', overall: 92, basePrice: 34000000, ageAtRetirement: 38, height: '177 cm', weight: '75 kg', peakClub: 'AC Milan', careerYears: '1994-2017', jerseyNumber: 21, captain: false, worldCupWinner: true, ballonDor: 0, championsLeague: 2, leagueTitles: 6, internationalCaps: 116, internationalGoals: 13, description: 'Deep-lying playmaker who changed the midfield position with his vision.', rarity: 'Mythic' },
  { name: 'Kaká', nickname: 'Ricky', country: 'Brazil', position: 'Midfielder', secondaryPositions: ['Forward'], preferredFoot: 'Right', overall: 93, basePrice: 36000000, ageAtRetirement: 35, height: '186 cm', weight: '78 kg', peakClub: 'AC Milan', careerYears: '2001-2017', jerseyNumber: 22, captain: false, worldCupWinner: true, ballonDor: 1, championsLeague: 1, leagueTitles: 2, internationalCaps: 92, internationalGoals: 29, description: 'Last player before Messi-Ronaldo era to win Ballon d\'Or. Grace and power.', rarity: 'Mythic' },
  { name: 'Ronaldinho', nickname: 'Ronnie', country: 'Brazil', position: 'Midfielder', secondaryPositions: ['Forward'], preferredFoot: 'Both', overall: 94, basePrice: 40000000, ageAtRetirement: 33, height: '182 cm', weight: '80 kg', peakClub: 'Barcelona', careerYears: '1998-2015', jerseyNumber: 10, captain: true, worldCupWinner: true, ballonDor: 1, championsLeague: 1, leagueTitles: 3, internationalCaps: 97, internationalGoals: 33, description: 'The most joyful footballer ever. Ballon d\'Or winner and World Cup champion.', rarity: 'Mythic' },
  { name: 'Steven Gerrard', nickname: 'Stevie G', country: 'England', position: 'Midfielder', secondaryPositions: ['Defender'], preferredFoot: 'Right', overall: 92, basePrice: 34000000, ageAtRetirement: 36, height: '183 cm', weight: '83 kg', peakClub: 'Liverpool', careerYears: '1998-2016', jerseyNumber: 8, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 0, internationalCaps: 114, internationalGoals: 21, description: 'Liverpool\'s iconic captain. One of the most complete midfielders ever.', rarity: 'Legend' },
  { name: 'Frank Lampard', nickname: 'Super Frank', country: 'England', position: 'Midfielder', secondaryPositions: [], preferredFoot: 'Right', overall: 91, basePrice: 32000000, ageAtRetirement: 38, height: '184 cm', weight: '80 kg', peakClub: 'Chelsea', careerYears: '1995-2017', jerseyNumber: 8, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 3, internationalCaps: 106, internationalGoals: 29, description: 'Highest-scoring midfielder in Premier League history. Chelsea legend.', rarity: 'Legend' },
  { name: 'Paul Scholes', nickname: 'Scholesy', country: 'England', position: 'Midfielder', secondaryPositions: [], preferredFoot: 'Right', overall: 91, basePrice: 30000000, ageAtRetirement: 38, height: '170 cm', weight: '72 kg', peakClub: 'Manchester United', careerYears: '1993-2013', jerseyNumber: 18, captain: false, worldCupWinner: false, ballonDor: 0, championsLeague: 2, leagueTitles: 11, internationalCaps: 66, internationalGoals: 14, description: 'Quiet genius. Possessed one of the best passing ranges in history.', rarity: 'Legend' },
  { name: 'Clarence Seedorf', nickname: 'Seedorf', country: 'Netherlands', position: 'Midfielder', secondaryPositions: [], preferredFoot: 'Both', overall: 90, basePrice: 28000000, ageAtRetirement: 37, height: '177 cm', weight: '79 kg', peakClub: 'AC Milan', careerYears: '1992-2014', jerseyNumber: 10, captain: false, worldCupWinner: false, ballonDor: 0, championsLeague: 5, leagueTitles: 4, internationalCaps: 87, internationalGoals: 11, description: 'Only player to win Champions League with three different clubs.', rarity: 'Legend' },
  { name: 'Patrick Vieira', nickname: 'Vieira', country: 'France', position: 'Midfielder', secondaryPositions: ['Defender'], preferredFoot: 'Right', overall: 90, basePrice: 28000000, ageAtRetirement: 35, height: '193 cm', weight: '86 kg', peakClub: 'Arsenal', careerYears: '1993-2011', jerseyNumber: 4, captain: true, worldCupWinner: true, ballonDor: 0, championsLeague: 0, leagueTitles: 4, internationalCaps: 107, internationalGoals: 6, description: 'Dominant box-to-box midfielder. The engine of Arsenal\'s Invincibles.', rarity: 'Legend' },
  { name: 'Claude Makélélé', nickname: 'Make', country: 'France', position: 'Midfielder', secondaryPositions: ['Defender'], preferredFoot: 'Right', overall: 88, basePrice: 20000000, ageAtRetirement: 36, height: '174 cm', weight: '68 kg', peakClub: 'Real Madrid', careerYears: '1992-2011', jerseyNumber: 6, captain: false, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 5, internationalCaps: 71, internationalGoals: 0, description: 'The position \'Makelele Role\' was named after him. Defensive midfield pioneer.', rarity: 'Legend' },
  { name: 'Sergio Busquets', nickname: 'Busi', country: 'Spain', position: 'Midfielder', secondaryPositions: ['Defender'], preferredFoot: 'Right', overall: 90, basePrice: 26000000, ageAtRetirement: 35, height: '189 cm', weight: '76 kg', peakClub: 'Barcelona', careerYears: '2005-2024', jerseyNumber: 5, captain: true, worldCupWinner: true, ballonDor: 0, championsLeague: 3, leagueTitles: 9, internationalCaps: 143, internationalGoals: 2, description: 'The best defensive midfielder of his generation. Master of positioning.', rarity: 'Legend' },
  { name: 'Xabi Alonso', nickname: 'Xabi', country: 'Spain', position: 'Midfielder', secondaryPositions: ['Defender'], preferredFoot: 'Right', overall: 90, basePrice: 28000000, ageAtRetirement: 35, height: '183 cm', weight: '80 kg', peakClub: 'Real Madrid', careerYears: '1999-2017', jerseyNumber: 14, captain: false, worldCupWinner: true, ballonDor: 0, championsLeague: 2, leagueTitles: 5, internationalCaps: 114, internationalGoals: 16, description: 'Elegant deep-lying playmaker with exceptional passing range.', rarity: 'Legend' },
  { name: 'Roy Keane', nickname: 'Keano', country: 'Ireland', position: 'Midfielder', secondaryPositions: ['Defender'], preferredFoot: 'Right', overall: 89, basePrice: 24000000, ageAtRetirement: 35, height: '180 cm', weight: '78 kg', peakClub: 'Manchester United', careerYears: '1989-2006', jerseyNumber: 16, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 7, internationalCaps: 67, internationalGoals: 9, description: 'Fierce midfield general. The driving force behind Manchester United\'s treble.', rarity: 'Legend' },
  { name: 'Michael Ballack', nickname: 'Ballack', country: 'Germany', position: 'Midfielder', secondaryPositions: [], preferredFoot: 'Right', overall: 90, basePrice: 26000000, ageAtRetirement: 35, height: '189 cm', weight: '85 kg', peakClub: 'Chelsea', careerYears: '1995-2012', jerseyNumber: 13, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 0, leagueTitles: 5, internationalCaps: 98, internationalGoals: 42, description: 'Powerful German leader. One of the best midfielders of his generation.', rarity: 'Legend' },
  { name: 'Toni Kroos', nickname: 'Kroos', country: 'Germany', position: 'Midfielder', secondaryPositions: [], preferredFoot: 'Right', overall: 91, basePrice: 30000000, ageAtRetirement: 34, height: '183 cm', weight: '78 kg', peakClub: 'Real Madrid', careerYears: '2007-2024', jerseyNumber: 8, captain: false, worldCupWinner: true, ballonDor: 0, championsLeague: 6, leagueTitles: 4, internationalCaps: 114, internationalGoals: 17, description: 'German precision. One of the best passers in football history.', rarity: 'Legend' },
  { name: 'David Beckham', nickname: 'Becks', country: 'England', position: 'Midfielder', secondaryPositions: [], preferredFoot: 'Right', overall: 88, basePrice: 24000000, ageAtRetirement: 38, height: '183 cm', weight: '74 kg', peakClub: 'Manchester United', careerYears: '1992-2013', jerseyNumber: 7, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 6, internationalCaps: 115, internationalGoals: 17, description: 'Global icon known for his incredible crossing and free-kick ability.', rarity: 'Legend' },
  { name: 'Luís Figo', nickname: 'Figo', country: 'Portugal', position: 'Midfielder', secondaryPositions: ['Forward'], preferredFoot: 'Right', overall: 92, basePrice: 38000000, ageAtRetirement: 37, height: '180 cm', weight: '75 kg', peakClub: 'Real Madrid', careerYears: '1989-2009', jerseyNumber: 7, captain: true, worldCupWinner: false, ballonDor: 1, championsLeague: 1, leagueTitles: 5, internationalCaps: 127, internationalGoals: 32, description: 'Ballon d\'Or winner. One of the greatest wingers of all time.', rarity: 'Legend' },
  { name: 'Pavel Nedvěd', nickname: 'Nedvěd', country: 'Czech Republic', position: 'Midfielder', secondaryPositions: ['Forward'], preferredFoot: 'Both', overall: 91, basePrice: 30000000, ageAtRetirement: 37, height: '177 cm', weight: '75 kg', peakClub: 'Juventus', careerYears: '1991-2009', jerseyNumber: 11, captain: true, worldCupWinner: false, ballonDor: 1, championsLeague: 0, leagueTitles: 5, internationalCaps: 91, internationalGoals: 18, description: 'Ballon d\'Or winner. Known for his relentless energy and powerful left foot.', rarity: 'Legend' },
  { name: 'Lothar Matthäus', nickname: 'Lothar', country: 'Germany', position: 'Midfielder', secondaryPositions: ['Defender'], preferredFoot: 'Right', overall: 94, basePrice: 40000000, ageAtRetirement: 39, height: '174 cm', weight: '72 kg', peakClub: 'Bayern Munich', careerYears: '1979-2000', jerseyNumber: 10, captain: true, worldCupWinner: true, ballonDor: 1, championsLeague: 1, leagueTitles: 7, internationalCaps: 150, internationalGoals: 23, description: 'Ballon d\'Or winner and World Cup winning captain. Complete footballer.', rarity: 'Mythic' },
  { name: 'Cesc Fàbregas', nickname: 'Cesc', country: 'Spain', position: 'Midfielder', secondaryPositions: ['Forward'], preferredFoot: 'Right', overall: 89, basePrice: 24000000, ageAtRetirement: 36, height: '179 cm', weight: '74 kg', peakClub: 'Arsenal', careerYears: '2003-2023', jerseyNumber: 4, captain: true, worldCupWinner: true, ballonDor: 0, championsLeague: 2, leagueTitles: 4, internationalCaps: 110, internationalGoals: 15, description: 'Creative genius with exceptional vision and passing. World Cup winner.', rarity: 'Legend' },
  { name: 'Yaya Touré', nickname: 'Yaya', country: 'Ivory Coast', position: 'Midfielder', secondaryPositions: ['Defender'], preferredFoot: 'Right', overall: 90, basePrice: 28000000, ageAtRetirement: 36, height: '188 cm', weight: '85 kg', peakClub: 'Manchester City', careerYears: '2001-2020', jerseyNumber: 42, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 0, leagueTitles: 4, internationalCaps: 108, internationalGoals: 19, description: 'Dominant box-to-box midfielder who defined Manchester City\'s rise.', rarity: 'Legend' },
  { name: 'Deco', nickname: 'Deco', country: 'Portugal', position: 'Midfielder', secondaryPositions: ['Forward'], preferredFoot: 'Right', overall: 88, basePrice: 20000000, ageAtRetirement: 35, height: '174 cm', weight: '70 kg', peakClub: 'Barcelona', careerYears: '1996-2013', jerseyNumber: 20, captain: false, worldCupWinner: false, ballonDor: 0, championsLeague: 2, leagueTitles: 4, internationalCaps: 75, internationalGoals: 10, description: 'Elegant playmaker who won Champions League with two clubs.', rarity: 'Icon' },
  { name: 'Juan Román Riquelme', nickname: 'Riquelme', country: 'Argentina', position: 'Midfielder', secondaryPositions: ['Forward'], preferredFoot: 'Right', overall: 89, basePrice: 22000000, ageAtRetirement: 36, height: '182 cm', weight: '75 kg', peakClub: 'Boca Juniors', careerYears: '1995-2015', jerseyNumber: 10, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 4, internationalCaps: 51, internationalGoals: 17, description: 'The last classic no.10. Mesmerizing dribbler and playmaker.', rarity: 'Legend' },
  { name: 'Rui Costa', nickname: 'Rui', country: 'Portugal', position: 'Midfielder', secondaryPositions: ['Forward'], preferredFoot: 'Right', overall: 88, basePrice: 20000000, ageAtRetirement: 35, height: '180 cm', weight: '76 kg', peakClub: 'AC Milan', careerYears: '1990-2008', jerseyNumber: 10, captain: false, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 2, internationalCaps: 94, internationalGoals: 26, description: 'Portuguese magician known for his incredible assists.', rarity: 'Icon' },
  { name: 'Rivaldo', nickname: 'Rivaldo', country: 'Brazil', position: 'Midfielder', secondaryPositions: ['Forward'], preferredFoot: 'Left', overall: 92, basePrice: 34000000, ageAtRetirement: 38, height: '186 cm', weight: '75 kg', peakClub: 'Barcelona', careerYears: '1989-2015', jerseyNumber: 10, captain: false, worldCupWinner: true, ballonDor: 1, championsLeague: 1, leagueTitles: 4, internationalCaps: 74, internationalGoals: 35, description: 'Ballon d\'Or winner. Spectacular striker with incredible technique.', rarity: 'Mythic' },
  { name: 'Michel Platini', nickname: 'Le Roi', country: 'France', position: 'Midfielder', secondaryPositions: ['Forward'], preferredFoot: 'Right', overall: 95, basePrice: 42000000, ageAtRetirement: 32, height: '179 cm', weight: '74 kg', peakClub: 'Juventus', careerYears: '1972-1987', jerseyNumber: 10, captain: true, worldCupWinner: false, ballonDor: 3, championsLeague: 1, leagueTitles: 6, internationalCaps: 72, internationalGoals: 41, description: 'Three-time Ballon d\'Or winner. One of the greatest playmakers ever.', rarity: 'Ultimate Legend' },
  { name: 'Gheorghe Hagi', nickname: 'The Maradona of the Carpathians', country: 'Romania', position: 'Midfielder', secondaryPositions: ['Forward'], preferredFoot: 'Left', overall: 88, basePrice: 20000000, ageAtRetirement: 36, height: '172 cm', weight: '70 kg', peakClub: 'Barcelona', careerYears: '1982-2001', jerseyNumber: 10, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 0, leagueTitles: 3, internationalCaps: 125, internationalGoals: 35, description: 'Romania\'s greatest ever player. Known for his spectacular left foot.', rarity: 'Legend' },
  { name: 'Wesley Sneijder', nickname: 'Sneijder', country: 'Netherlands', position: 'Midfielder', secondaryPositions: ['Forward'], preferredFoot: 'Right', overall: 89, basePrice: 24000000, ageAtRetirement: 34, height: '170 cm', weight: '67 kg', peakClub: 'Inter Milan', careerYears: '2002-2019', jerseyNumber: 10, captain: false, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 4, internationalCaps: 133, internationalGoals: 31, description: 'Led Inter to treble and Netherlands to World Cup final in 2010.', rarity: 'Legend' },
  { name: 'Mesut Özil', nickname: 'Özil', country: 'Germany', position: 'Midfielder', secondaryPositions: ['Forward'], preferredFoot: 'Left', overall: 88, basePrice: 22000000, ageAtRetirement: 33, height: '180 cm', weight: '76 kg', peakClub: 'Real Madrid', careerYears: '2006-2023', jerseyNumber: 10, captain: false, worldCupWinner: true, ballonDor: 0, championsLeague: 0, leagueTitles: 2, internationalCaps: 92, internationalGoals: 23, description: 'One of the most creative playmakers of his generation. World Cup winner.', rarity: 'Legend' },
  { name: 'Edgar Davids', nickname: 'The Pitbull', country: 'Netherlands', position: 'Midfielder', secondaryPositions: ['Defender'], preferredFoot: 'Left', overall: 87, basePrice: 16000000, ageAtRetirement: 36, height: '169 cm', weight: '70 kg', peakClub: 'Ajax', careerYears: '1991-2014', jerseyNumber: 8, captain: false, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 5, internationalCaps: 74, internationalGoals: 6, description: 'Recognizable by his goggles. Tenacious midfield dynamo.', rarity: 'Icon' },
  { name: 'Gennaro Gattuso', nickname: 'Rino', country: 'Italy', position: 'Midfielder', secondaryPositions: ['Defender'], preferredFoot: 'Right', overall: 86, basePrice: 14000000, ageAtRetirement: 35, height: '177 cm', weight: '76 kg', peakClub: 'AC Milan', careerYears: '1994-2013', jerseyNumber: 8, captain: false, worldCupWinner: true, ballonDor: 0, championsLeague: 2, leagueTitles: 3, internationalCaps: 73, internationalGoals: 1, description: 'The ultimate midfield enforcer. World Cup winner with Italy.', rarity: 'Icon' },
  { name: 'Fernando Redondo', nickname: 'El Príncipe', country: 'Argentina', position: 'Midfielder', secondaryPositions: ['Defender'], preferredFoot: 'Left', overall: 88, basePrice: 18000000, ageAtRetirement: 33, height: '186 cm', weight: '78 kg', peakClub: 'Real Madrid', careerYears: '1985-2004', jerseyNumber: 6, captain: false, worldCupWinner: false, ballonDor: 0, championsLeague: 2, leagueTitles: 3, internationalCaps: 29, internationalGoals: 1, description: 'Elegant defensive midfielder. His backheel vs Man United is legendary.', rarity: 'Icon' },
  { name: 'Dunga', nickname: 'Dunga', country: 'Brazil', position: 'Midfielder', secondaryPositions: ['Defender'], preferredFoot: 'Right', overall: 86, basePrice: 12000000, ageAtRetirement: 36, height: '177 cm', weight: '75 kg', peakClub: 'Brazil', careerYears: '1982-2000', jerseyNumber: 8, captain: true, worldCupWinner: true, ballonDor: 0, championsLeague: 0, leagueTitles: 2, internationalCaps: 91, internationalGoals: 6, description: 'World Cup winning captain who led Brazil to glory in 1994.', rarity: 'Icon' },

  // ===================== FORWARDS (44) =====================
  { name: 'Lionel Messi', nickname: 'La Pulga', country: 'Argentina', position: 'Forward', secondaryPositions: ['Midfielder'], preferredFoot: 'Left', overall: 99, basePrice: 80000000, ageAtRetirement: 38, height: '170 cm', weight: '72 kg', peakClub: 'Barcelona', careerYears: '2004-2025', jerseyNumber: 10, captain: true, worldCupWinner: true, ballonDor: 8, championsLeague: 4, leagueTitles: 12, internationalCaps: 191, internationalGoals: 112, description: 'The greatest of all time. 8 Ballon d\'Ors, World Cup winner, record breaker.', rarity: 'Ultimate Legend' },
  { name: 'Cristiano Ronaldo', nickname: 'CR7', country: 'Portugal', position: 'Forward', secondaryPositions: ['Midfielder'], preferredFoot: 'Right', overall: 98, basePrice: 75000000, ageAtRetirement: 39, height: '187 cm', weight: '85 kg', peakClub: 'Real Madrid', careerYears: '2002-2025', jerseyNumber: 7, captain: true, worldCupWinner: false, ballonDor: 5, championsLeague: 5, leagueTitles: 7, internationalCaps: 217, internationalGoals: 133, description: 'One of the two greatest ever. 5 Ballon d\'Ors, 5 Champions Leagues.', rarity: 'Ultimate Legend' },
  { name: 'Pelé', nickname: 'O Rei', country: 'Brazil', position: 'Forward', secondaryPositions: ['Midfielder'], preferredFoot: 'Right', overall: 98, basePrice: 70000000, ageAtRetirement: 37, height: '173 cm', weight: '74 kg', peakClub: 'Santos', careerYears: '1956-1977', jerseyNumber: 10, captain: true, worldCupWinner: true, ballonDor: 0, championsLeague: 0, leagueTitles: 6, internationalCaps: 92, internationalGoals: 77, description: 'The original King of Football. Only player to win 3 World Cups.', rarity: 'Ultimate Legend' },
  { name: 'Diego Maradona', nickname: 'El Pibe de Oro', country: 'Argentina', position: 'Forward', secondaryPositions: ['Midfielder'], preferredFoot: 'Left', overall: 97, basePrice: 65000000, ageAtRetirement: 37, height: '165 cm', weight: '70 kg', peakClub: 'Napoli', careerYears: '1976-1997', jerseyNumber: 10, captain: true, worldCupWinner: true, ballonDor: 0, championsLeague: 0, leagueTitles: 3, internationalCaps: 91, internationalGoals: 34, description: 'One of the most gifted players ever. The Hand of God and Goal of the Century.', rarity: 'Ultimate Legend' },
  { name: 'Ronaldo Nazário', nickname: 'O Fenômeno', country: 'Brazil', position: 'Forward', secondaryPositions: [], preferredFoot: 'Both', overall: 96, basePrice: 55000000, ageAtRetirement: 34, height: '183 cm', weight: '82 kg', peakClub: 'Barcelona', careerYears: '1993-2011', jerseyNumber: 9, captain: false, worldCupWinner: true, ballonDor: 2, championsLeague: 0, leagueTitles: 2, internationalCaps: 98, internationalGoals: 62, description: 'The most devastating striker in history. Two-time World Cup winner and Ballon d\'Or.', rarity: 'Ultimate Legend' },
  { name: 'Neymar Jr.', nickname: 'Ney', country: 'Brazil', position: 'Forward', secondaryPositions: ['Midfielder'], preferredFoot: 'Right', overall: 92, basePrice: 38000000, ageAtRetirement: 33, height: '175 cm', weight: '68 kg', peakClub: 'Barcelona', careerYears: '2009-2025', jerseyNumber: 10, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 4, internationalCaps: 128, internationalGoals: 79, description: 'Brazilian magician known for his flair, dribbling and goalscoring.', rarity: 'Legend' },
  { name: 'Romário', nickname: 'Baixinho', country: 'Brazil', position: 'Forward', secondaryPositions: [], preferredFoot: 'Right', overall: 93, basePrice: 35000000, ageAtRetirement: 41, height: '169 cm', weight: '70 kg', peakClub: 'Barcelona', careerYears: '1985-2007', jerseyNumber: 11, captain: false, worldCupWinner: true, ballonDor: 1, championsLeague: 0, leagueTitles: 4, internationalCaps: 70, internationalGoals: 55, description: 'World Cup winner and Ballon d\'Or winner. Lethal finisher.', rarity: 'Mythic' },
  { name: 'Thierry Henry', nickname: 'Titi', country: 'France', position: 'Forward', secondaryPositions: ['Midfielder'], preferredFoot: 'Right', overall: 93, basePrice: 38000000, ageAtRetirement: 37, height: '188 cm', weight: '83 kg', peakClub: 'Arsenal', careerYears: '1994-2014', jerseyNumber: 14, captain: true, worldCupWinner: true, ballonDor: 0, championsLeague: 1, leagueTitles: 4, internationalCaps: 123, internationalGoals: 51, description: 'Arsenal\'s all-time top scorer. Premier League legend and World Cup winner.', rarity: 'Mythic' },
  { name: 'Marco van Basten', nickname: 'San Marco', country: 'Netherlands', position: 'Forward', secondaryPositions: [], preferredFoot: 'Right', overall: 94, basePrice: 40000000, ageAtRetirement: 31, height: '188 cm', weight: '80 kg', peakClub: 'AC Milan', careerYears: '1981-1995', jerseyNumber: 9, captain: false, worldCupWinner: false, ballonDor: 3, championsLeague: 1, leagueTitles: 5, internationalCaps: 58, internationalGoals: 24, description: 'Three-time Ballon d\'Or winner. The complete striker.', rarity: 'Mythic' },
  { name: 'Didier Drogba', nickname: 'The King', country: 'Ivory Coast', position: 'Forward', secondaryPositions: [], preferredFoot: 'Right', overall: 91, basePrice: 32000000, ageAtRetirement: 38, height: '189 cm', weight: '91 kg', peakClub: 'Chelsea', careerYears: '1998-2018', jerseyNumber: 11, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 4, internationalCaps: 104, internationalGoals: 65, description: 'Chelsea legend who scored in big finals. African football icon.', rarity: 'Legend' },
  { name: 'Samuel Eto\'o', nickname: 'La Pantera', country: 'Cameroon', position: 'Forward', secondaryPositions: ['Midfielder'], preferredFoot: 'Right', overall: 91, basePrice: 30000000, ageAtRetirement: 37, height: '180 cm', weight: '79 kg', peakClub: 'Barcelona', careerYears: '1997-2019', jerseyNumber: 9, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 3, leagueTitles: 5, internationalCaps: 118, internationalGoals: 56, description: 'One of Africa\'s greatest. Won the treble twice with two different clubs.', rarity: 'Legend' },
  { name: 'Zlatan Ibrahimović', nickname: 'Ibracadabra', country: 'Sweden', position: 'Forward', secondaryPositions: [], preferredFoot: 'Right', overall: 92, basePrice: 35000000, ageAtRetirement: 41, height: '195 cm', weight: '95 kg', peakClub: 'AC Milan', careerYears: '1999-2023', jerseyNumber: 9, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 0, leagueTitles: 14, internationalCaps: 122, internationalGoals: 62, description: 'One of the most charismatic and prolific strikers of all time.', rarity: 'Legend' },
  { name: 'Luis Suárez', nickname: 'El Pistolero', country: 'Uruguay', position: 'Forward', secondaryPositions: [], preferredFoot: 'Right', overall: 92, basePrice: 34000000, ageAtRetirement: 37, height: '182 cm', weight: '86 kg', peakClub: 'Barcelona', careerYears: '2005-2024', jerseyNumber: 9, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 6, internationalCaps: 143, internationalGoals: 69, description: 'One of the best strikers of his generation. European Golden Shoe winner.', rarity: 'Legend' },
  { name: 'Robert Lewandowski', nickname: 'Lewy', country: 'Poland', position: 'Forward', secondaryPositions: [], preferredFoot: 'Right', overall: 93, basePrice: 38000000, ageAtRetirement: 35, height: '185 cm', weight: '81 kg', peakClub: 'Bayern Munich', careerYears: '2005-2025', jerseyNumber: 9, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 10, internationalCaps: 156, internationalGoals: 84, description: 'One of the most complete strikers ever. Record-breaking goalscorer.', rarity: 'Legend' },
  { name: 'Karim Benzema', nickname: 'El Gato', country: 'France', position: 'Forward', secondaryPositions: [], preferredFoot: 'Right', overall: 92, basePrice: 34000000, ageAtRetirement: 36, height: '185 cm', weight: '81 kg', peakClub: 'Real Madrid', careerYears: '2004-2024', jerseyNumber: 9, captain: true, worldCupWinner: false, ballonDor: 1, championsLeague: 5, leagueTitles: 4, internationalCaps: 97, internationalGoals: 37, description: 'Ballon d\'Or winner. Real Madrid\'s second all-time top scorer.', rarity: 'Legend' },
  { name: 'Wayne Rooney', nickname: 'Wazza', country: 'England', position: 'Forward', secondaryPositions: ['Midfielder'], preferredFoot: 'Right', overall: 91, basePrice: 30000000, ageAtRetirement: 35, height: '176 cm', weight: '78 kg', peakClub: 'Manchester United', careerYears: '2002-2020', jerseyNumber: 10, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 5, internationalCaps: 120, internationalGoals: 53, description: 'Manchester United and England all-time top scorer. Complete forward.', rarity: 'Legend' },
  { name: 'David Villa', nickname: 'El Guaje', country: 'Spain', position: 'Forward', secondaryPositions: ['Midfielder'], preferredFoot: 'Right', overall: 90, basePrice: 26000000, ageAtRetirement: 36, height: '175 cm', weight: '69 kg', peakClub: 'Barcelona', careerYears: '2000-2020', jerseyNumber: 7, captain: false, worldCupWinner: true, ballonDor: 0, championsLeague: 1, leagueTitles: 4, internationalCaps: 98, internationalGoals: 59, description: 'Spain\'s all-time top scorer. World Cup and European Championship winner.', rarity: 'Legend' },
  { name: 'Gabriel Batistuta', nickname: 'Batigol', country: 'Argentina', position: 'Forward', secondaryPositions: [], preferredFoot: 'Right', overall: 91, basePrice: 30000000, ageAtRetirement: 35, height: '185 cm', weight: '80 kg', peakClub: 'Fiorentina', careerYears: '1988-2005', jerseyNumber: 9, captain: false, worldCupWinner: false, ballonDor: 0, championsLeague: 0, leagueTitles: 1, internationalCaps: 78, internationalGoals: 56, description: 'One of the most powerful strikers ever. Fiorentina legend.', rarity: 'Legend' },
  { name: 'Alan Shearer', nickname: 'Shearer', country: 'England', position: 'Forward', secondaryPositions: [], preferredFoot: 'Right', overall: 91, basePrice: 28000000, ageAtRetirement: 35, height: '183 cm', weight: '79 kg', peakClub: 'Newcastle United', careerYears: '1988-2006', jerseyNumber: 9, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 0, leagueTitles: 1, internationalCaps: 63, internationalGoals: 30, description: 'Premier League all-time top scorer. Newcastle icon.', rarity: 'Legend' },
  { name: 'Ruud van Nistelrooy', nickname: 'Ruud', country: 'Netherlands', position: 'Forward', secondaryPositions: [], preferredFoot: 'Right', overall: 90, basePrice: 28000000, ageAtRetirement: 35, height: '188 cm', weight: '80 kg', peakClub: 'Manchester United', careerYears: '1993-2012', jerseyNumber: 10, captain: false, worldCupWinner: false, ballonDor: 0, championsLeague: 0, leagueTitles: 3, internationalCaps: 70, internationalGoals: 35, description: 'One of the deadliest penalty box strikers in history.', rarity: 'Legend' },
  { name: 'Dennis Bergkamp', nickname: 'The Non-Flying Dutchman', country: 'Netherlands', position: 'Forward', secondaryPositions: ['Midfielder'], preferredFoot: 'Right', overall: 91, basePrice: 30000000, ageAtRetirement: 37, height: '183 cm', weight: '78 kg', peakClub: 'Arsenal', careerYears: '1986-2006', jerseyNumber: 10, captain: false, worldCupWinner: false, ballonDor: 0, championsLeague: 0, leagueTitles: 3, internationalCaps: 79, internationalGoals: 37, description: 'Arsenal legend known for his sublime technique and vision.', rarity: 'Legend' },
  { name: 'Fernando Torres', nickname: 'El Niño', country: 'Spain', position: 'Forward', secondaryPositions: [], preferredFoot: 'Right', overall: 89, basePrice: 24000000, ageAtRetirement: 35, height: '186 cm', weight: '81 kg', peakClub: 'Atlético Madrid', careerYears: '2001-2019', jerseyNumber: 9, captain: true, worldCupWinner: true, ballonDor: 0, championsLeague: 1, leagueTitles: 2, internationalCaps: 110, internationalGoals: 38, description: 'World Cup and European Championship winner. Scored winning Euro 2008 goal.', rarity: 'Legend' },
  { name: 'George Weah', nickname: 'Weah', country: 'Liberia', position: 'Forward', secondaryPositions: ['Midfielder'], preferredFoot: 'Right', overall: 88, basePrice: 22000000, ageAtRetirement: 37, height: '184 cm', weight: '80 kg', peakClub: 'AC Milan', careerYears: '1985-2003', jerseyNumber: 14, captain: true, worldCupWinner: false, ballonDor: 1, championsLeague: 0, leagueTitles: 2, internationalCaps: 60, internationalGoals: 13, description: 'The only African to win Ballon d\'Or. Later became President of Liberia.', rarity: 'Mythic' },
  { name: 'George Best', nickname: 'The Fifth Beatle', country: 'Northern Ireland', position: 'Forward', secondaryPositions: ['Midfielder'], preferredFoot: 'Left', overall: 93, basePrice: 35000000, ageAtRetirement: 30, height: '175 cm', weight: '70 kg', peakClub: 'Manchester United', careerYears: '1963-1984', jerseyNumber: 7, captain: false, worldCupWinner: false, ballonDor: 1, championsLeague: 1, leagueTitles: 2, internationalCaps: 37, internationalGoals: 9, description: 'One of the most naturally gifted players ever. Ballon d\'Or winner.', rarity: 'Mythic' },
  { name: 'Garrincha', nickname: 'The Little Bird', country: 'Brazil', position: 'Forward', secondaryPositions: ['Midfielder'], preferredFoot: 'Both', overall: 94, basePrice: 38000000, ageAtRetirement: 33, height: '169 cm', weight: '72 kg', peakClub: 'Botafogo', careerYears: '1951-1972', jerseyNumber: 7, captain: false, worldCupWinner: true, ballonDor: 0, championsLeague: 0, leagueTitles: 2, internationalCaps: 50, internationalGoals: 12, description: 'The greatest dribbler in history. Two-time World Cup winner.', rarity: 'Mythic' },
  { name: 'Jairzinho', nickname: 'Jairzinho', country: 'Brazil', position: 'Forward', secondaryPositions: ['Midfielder'], preferredFoot: 'Right', overall: 90, basePrice: 26000000, ageAtRetirement: 33, height: '173 cm', weight: '75 kg', peakClub: 'Botafogo', careerYears: '1962-1982', jerseyNumber: 7, captain: false, worldCupWinner: true, ballonDor: 0, championsLeague: 0, leagueTitles: 1, internationalCaps: 81, internationalGoals: 33, description: 'Scored in every match of Brazil\'s 1970 World Cup triumph.', rarity: 'Legend' },
  { name: 'Hristo Stoichkov', nickname: 'The Dagger', country: 'Bulgaria', position: 'Forward', secondaryPositions: ['Midfielder'], preferredFoot: 'Left', overall: 90, basePrice: 26000000, ageAtRetirement: 34, height: '178 cm', weight: '78 kg', peakClub: 'Barcelona', careerYears: '1981-2000', jerseyNumber: 8, captain: true, worldCupWinner: false, ballonDor: 1, championsLeague: 1, leagueTitles: 5, internationalCaps: 83, internationalGoals: 37, description: 'Ballon d\'Or winner. Bulgarian legend with a fearsome left foot.', rarity: 'Legend' },
  { name: 'Arjen Robben', nickname: 'Robben', country: 'Netherlands', position: 'Forward', secondaryPositions: ['Midfielder'], preferredFoot: 'Left', overall: 90, basePrice: 28000000, ageAtRetirement: 35, height: '180 cm', weight: '80 kg', peakClub: 'Bayern Munich', careerYears: '2000-2021', jerseyNumber: 10, captain: false, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 8, internationalCaps: 96, internationalGoals: 37, description: 'Famous for cutting inside from the right. Dutch legend.', rarity: 'Legend' },
  { name: 'Ryan Giggs', nickname: 'Giggsy', country: 'Wales', position: 'Forward', secondaryPositions: ['Midfielder'], preferredFoot: 'Left', overall: 89, basePrice: 24000000, ageAtRetirement: 40, height: '179 cm', weight: '74 kg', peakClub: 'Manchester United', careerYears: '1990-2014', jerseyNumber: 11, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 2, leagueTitles: 13, internationalCaps: 64, internationalGoals: 12, description: 'Most decorated player in English football history. The ultimate winger.', rarity: 'Legend' },
  { name: 'Franck Ribéry', nickname: 'Kaiser Franck', country: 'France', position: 'Forward', secondaryPositions: ['Midfielder'], preferredFoot: 'Right', overall: 89, basePrice: 26000000, ageAtRetirement: 36, height: '170 cm', weight: '72 kg', peakClub: 'Bayern Munich', careerYears: '2000-2022', jerseyNumber: 7, captain: true, worldCupWinner: true, ballonDor: 0, championsLeague: 1, leagueTitles: 9, internationalCaps: 81, internationalGoals: 16, description: 'French wizard who formed one of the best wing duos in history.', rarity: 'Legend' },
  { name: 'Eden Hazard', nickname: 'Hazard', country: 'Belgium', position: 'Forward', secondaryPositions: ['Midfielder'], preferredFoot: 'Right', overall: 91, basePrice: 32000000, ageAtRetirement: 32, height: '175 cm', weight: '76 kg', peakClub: 'Chelsea', careerYears: '2007-2023', jerseyNumber: 10, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 3, internationalCaps: 126, internationalGoals: 33, description: 'One of the most skillful players of his generation. Chelsea legend.', rarity: 'Legend' },
  { name: 'Mohamed Salah', nickname: 'Mo', country: 'Egypt', position: 'Forward', secondaryPositions: ['Midfielder'], preferredFoot: 'Left', overall: 91, basePrice: 32000000, ageAtRetirement: 33, height: '175 cm', weight: '71 kg', peakClub: 'Liverpool', careerYears: '2010-2025', jerseyNumber: 11, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 1, internationalCaps: 105, internationalGoals: 59, description: 'Egyptian King. Premier League record breaker and Liverpool icon.', rarity: 'Legend' },
  { name: 'Ángel Di María', nickname: 'Fideo', country: 'Argentina', position: 'Forward', secondaryPositions: ['Midfielder'], preferredFoot: 'Left', overall: 88, basePrice: 24000000, ageAtRetirement: 36, height: '180 cm', weight: '75 kg', peakClub: 'Real Madrid', careerYears: '2005-2025', jerseyNumber: 22, captain: false, worldCupWinner: true, ballonDor: 0, championsLeague: 1, leagueTitles: 5, internationalCaps: 145, internationalGoals: 33, description: 'World Cup winner who scored in the 2022 final. Big game player.', rarity: 'Legend' },
  { name: 'Michael Owen', nickname: 'Mighty Mouse', country: 'England', position: 'Forward', secondaryPositions: ['Midfielder'], preferredFoot: 'Right', overall: 89, basePrice: 24000000, ageAtRetirement: 33, height: '173 cm', weight: '70 kg', peakClub: 'Liverpool', careerYears: '1996-2013', jerseyNumber: 10, captain: false, worldCupWinner: false, ballonDor: 1, championsLeague: 0, leagueTitles: 1, internationalCaps: 89, internationalGoals: 40, description: 'Ballon d\'Or winner. Known for his blistering pace.', rarity: 'Legend' },
  { name: 'Christian Vieri', nickname: 'Bobo', country: 'Italy', position: 'Forward', secondaryPositions: [], preferredFoot: 'Right', overall: 89, basePrice: 22000000, ageAtRetirement: 36, height: '186 cm', weight: '85 kg', peakClub: 'Inter Milan', careerYears: '1989-2009', jerseyNumber: 32, captain: false, worldCupWinner: false, ballonDor: 0, championsLeague: 0, leagueTitles: 0, internationalCaps: 49, internationalGoals: 23, description: 'Powerful striker who was the most expensive player in the world.', rarity: 'Icon' },
  { name: 'Hernán Crespo', nickname: 'Valdanito', country: 'Argentina', position: 'Forward', secondaryPositions: [], preferredFoot: 'Right', overall: 88, basePrice: 20000000, ageAtRetirement: 35, height: '184 cm', weight: '80 kg', peakClub: 'Parma', careerYears: '1993-2012', jerseyNumber: 9, captain: false, worldCupWinner: false, ballonDor: 0, championsLeague: 0, leagueTitles: 3, internationalCaps: 64, internationalGoals: 35, description: 'Elegant Argentine striker with lethal finishing.', rarity: 'Icon' },
  { name: 'Robin van Persie', nickname: 'RVP', country: 'Netherlands', position: 'Forward', secondaryPositions: ['Midfielder'], preferredFoot: 'Left', overall: 89, basePrice: 26000000, ageAtRetirement: 36, height: '183 cm', weight: '78 kg', peakClub: 'Arsenal', careerYears: '2000-2019', jerseyNumber: 20, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 0, leagueTitles: 2, internationalCaps: 102, internationalGoals: 50, description: 'Known for his flying header against Spain. Dutch all-time top scorer.', rarity: 'Legend' },
  { name: 'Kenny Dalglish', nickname: 'King Kenny', country: 'Scotland', position: 'Forward', secondaryPositions: ['Midfielder'], preferredFoot: 'Right', overall: 91, basePrice: 28000000, ageAtRetirement: 36, height: '173 cm', weight: '72 kg', peakClub: 'Liverpool', careerYears: '1968-1990', jerseyNumber: 7, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 8, internationalCaps: 102, internationalGoals: 30, description: 'Liverpool\'s greatest ever player. Legend as player and manager.', rarity: 'Legend' },
  { name: 'Ian Rush', nickname: 'Rushie', country: 'Wales', position: 'Forward', secondaryPositions: [], preferredFoot: 'Right', overall: 89, basePrice: 22000000, ageAtRetirement: 36, height: '180 cm', weight: '74 kg', peakClub: 'Liverpool', careerYears: '1978-1999', jerseyNumber: 9, captain: false, worldCupWinner: false, ballonDor: 0, championsLeague: 0, leagueTitles: 5, internationalCaps: 73, internationalGoals: 28, description: 'Liverpool\'s all-time top scorer with 346 goals.', rarity: 'Legend' },
  { name: 'Hugo Sánchez', nickname: 'Hugol', country: 'Mexico', position: 'Forward', secondaryPositions: [], preferredFoot: 'Right', overall: 89, basePrice: 22000000, ageAtRetirement: 36, height: '175 cm', weight: '74 kg', peakClub: 'Real Madrid', careerYears: '1976-1998', jerseyNumber: 7, captain: false, worldCupWinner: false, ballonDor: 0, championsLeague: 0, leagueTitles: 5, internationalCaps: 145, internationalGoals: 48, description: 'Mexican legend known for his acrobatic goals and iconic backflip celebration.', rarity: 'Legend' },
  { name: 'Filippo Inzaghi', nickname: 'Superpippo', country: 'Italy', position: 'Forward', secondaryPositions: [], preferredFoot: 'Right', overall: 87, basePrice: 18000000, ageAtRetirement: 39, height: '181 cm', weight: '78 kg', peakClub: 'AC Milan', careerYears: '1991-2012', jerseyNumber: 9, captain: false, worldCupWinner: true, ballonDor: 0, championsLeague: 2, leagueTitles: 3, internationalCaps: 57, internationalGoals: 25, description: 'The ultimate poacher. Lived on the shoulder of the last defender.', rarity: 'Icon' },
  { name: 'Emilio Butragueño', nickname: 'El Buitre', country: 'Spain', position: 'Forward', secondaryPositions: [], preferredFoot: 'Right', overall: 86, basePrice: 16000000, ageAtRetirement: 33, height: '172 cm', weight: '68 kg', peakClub: 'Real Madrid', careerYears: '1981-1998', jerseyNumber: 7, captain: false, worldCupWinner: false, ballonDor: 0, championsLeague: 2, leagueTitles: 6, internationalCaps: 69, internationalGoals: 26, description: 'Real Madrid legend and part of the famous \'La Quinta del Buitre\'.', rarity: 'Icon' },
  { name: 'Miroslav Klose', nickname: 'Miro', country: 'Germany', position: 'Forward', secondaryPositions: [], preferredFoot: 'Right', overall: 89, basePrice: 22000000, ageAtRetirement: 36, height: '184 cm', weight: '82 kg', peakClub: 'Bayern Munich', careerYears: '1999-2016', jerseyNumber: 11, captain: false, worldCupWinner: true, ballonDor: 0, championsLeague: 0, leagueTitles: 3, internationalCaps: 137, internationalGoals: 71, description: 'All-time World Cup top scorer with 16 goals. German legend.', rarity: 'Legend' },
  { name: 'Sadio Mané', nickname: 'Mané', country: 'Senegal', position: 'Forward', secondaryPositions: ['Midfielder'], preferredFoot: 'Right', overall: 90, basePrice: 28000000, ageAtRetirement: 33, height: '174 cm', weight: '76 kg', peakClub: 'Liverpool', careerYears: '2011-2025', jerseyNumber: 10, captain: true, worldCupWinner: false, ballonDor: 0, championsLeague: 1, leagueTitles: 1, internationalCaps: 114, internationalGoals: 43, description: 'Senegal\'s greatest ever player. African Cup of Nations and Champions League winner.', rarity: 'Legend' },
];

const handler = async () => {
  try {
    const uri = process.env.MONGODB_URI;
    if (!uri) {
      console.error('MONGODB_URI not found in environment variables');
      process.exit(1);
    }

    await mongoose.connect(uri);
    console.log('Connected to MongoDB');

    await Player.deleteMany({});
    console.log('Cleared existing players');

    const result = await Player.insertMany(legends);
    console.log(`Seeded ${result.length} football legends`);

    await mongoose.connection.close();
    console.log('Database connection closed');
    process.exit(0);
  } catch (error) {
    console.error('Seeding error:', error);
    process.exit(1);
  }
};

handler();
