import mongoose from 'mongoose';

const managerSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true,
    trim: true,
  },
  nickname: {
    type: String,
    default: '',
  },
  nationality: {
    type: String,
    required: true,
  },
  image: {
    type: String,
    default: '',
  },
  preferredFormation: {
    type: String,
    enum: ['4-3-3', '4-2-3-1', '4-4-2', '3-5-2', '3-4-3', '5-3-2', '5-4-1', '4-1-4-1', '4-3-2-1', '4-2-2-2'],
    default: '4-3-3',
  },
  tacticalStyle: {
    type: String,
    enum: ['Tiki-Taka', 'Gegenpressing', 'Park the Bus', 'Counter-Attack', 'Total Football', 'Catenaccio', 'Direct Football', 'Possession', 'Long Ball', 'Wing Play'],
    required: true,
  },
  rating: {
    type: Number,
    required: true,
    min: 70,
    max: 99,
  },
  description: {
    type: String,
    default: '',
  },
  trophies: {
    type: Number,
    default: 0,
  },
}, {
  timestamps: true,
});

export const managersData = [
  {
    name: 'Sir Alex Ferguson',
    nickname: 'The Boss',
    nationality: 'Scotland',
    preferredFormation: '4-4-2',
    tacticalStyle: 'Wing Play',
    rating: 99,
    description: 'The greatest manager of all time. 38 trophies in 26 years at Manchester United.',
    trophies: 38,
  },
  {
    name: 'Pep Guardiola',
    nickname: 'The Philosopher',
    nationality: 'Spain',
    preferredFormation: '4-3-3',
    tacticalStyle: 'Tiki-Taka',
    rating: 98,
    description: 'Tactical genius who revolutionized modern football with possession-based football.',
    trophies: 35,
  },
  {
    name: 'José Mourinho',
    nickname: 'The Special One',
    nationality: 'Portugal',
    preferredFormation: '4-2-3-1',
    tacticalStyle: 'Counter-Attack',
    rating: 94,
    description: 'Master of defensive organization and counter-attacking football.',
    trophies: 26,
  },
  {
    name: 'Carlo Ancelotti',
    nickname: 'Don Carlo',
    nationality: 'Italy',
    preferredFormation: '4-3-3',
    tacticalStyle: 'Possession',
    rating: 95,
    description: 'The only manager to win league titles in all top 5 European leagues.',
    trophies: 28,
  },
  {
    name: 'Jürgen Klopp',
    nickname: 'The Normal One',
    nationality: 'Germany',
    preferredFormation: '4-3-3',
    tacticalStyle: 'Gegenpressing',
    rating: 93,
    description: 'Heavy metal football. Known for intense pressing and emotional leadership.',
    trophies: 14,
  },
  {
    name: 'Arsène Wenger',
    nickname: 'Le Professeur',
    nationality: 'France',
    preferredFormation: '4-3-3',
    tacticalStyle: 'Total Football',
    rating: 91,
    description: 'Revolutionized English football with diet, sports science, and attacking football.',
    trophies: 17,
  },
  {
    name: 'Vicente del Bosque',
    nickname: 'El Sabio',
    nationality: 'Spain',
    preferredFormation: '4-3-3',
    tacticalStyle: 'Tiki-Taka',
    rating: 92,
    description: 'Led Spain to their first World Cup and defended the European Championship.',
    trophies: 11,
  },
  {
    name: 'Marcello Lippi',
    nickname: 'The Maestro',
    nationality: 'Italy',
    preferredFormation: '4-4-2',
    tacticalStyle: 'Catenaccio',
    rating: 90,
    description: 'Won the World Cup with Italy and led Juventus to Champions League glory.',
    trophies: 18,
  },
  {
    name: 'Johan Cruyff',
    nickname: 'The Prophet',
    nationality: 'Netherlands',
    preferredFormation: '3-4-3',
    tacticalStyle: 'Total Football',
    rating: 96,
    description: 'The father of Total Football. Changed Barcelona and football forever.',
    trophies: 14,
  },
  {
    name: 'Zinedine Zidane',
    nickname: 'ZZ',
    nationality: 'France',
    preferredFormation: '4-3-3',
    tacticalStyle: 'Possession',
    rating: 92,
    description: 'Three consecutive Champions League titles. A legend as player and manager.',
    trophies: 11,
  },
  {
    name: 'Luis Enrique',
    nickname: 'Lucho',
    nationality: 'Spain',
    preferredFormation: '4-3-3',
    tacticalStyle: 'Gegenpressing',
    rating: 88,
    description: 'Won the treble with Barcelona in his first season in charge.',
    trophies: 11,
  },
  {
    name: 'Diego Simeone',
    nickname: 'El Cholo',
    nationality: 'Argentina',
    preferredFormation: '4-4-2',
    tacticalStyle: 'Park the Bus',
    rating: 89,
    description: 'Transformed Atlético Madrid into a European powerhouse with grit and discipline.',
    trophies: 9,
  },
  {
    name: 'Fabio Capello',
    nickname: 'The General',
    nationality: 'Italy',
    preferredFormation: '4-4-2',
    tacticalStyle: 'Catenaccio',
    rating: 88,
    description: 'Known for his disciplined, defensively solid teams across Europe.',
    trophies: 16,
  },
  {
    name: 'Ottmar Hitzfeld',
    nickname: 'The General',
    nationality: 'Germany',
    preferredFormation: '4-3-3',
    tacticalStyle: 'Direct Football',
    rating: 87,
    description: 'One of the most successful German managers with two Champions League titles.',
    trophies: 18,
  },
  {
    name: 'Antonio Conte',
    nickname: 'The Master of 3-5-2',
    nationality: 'Italy',
    preferredFormation: '3-5-2',
    tacticalStyle: 'Gegenpressing',
    rating: 87,
    description: 'Tactical master who revived the 3-5-2 formation in modern football.',
    trophies: 11,
  },
];

export default mongoose.model('Manager', managerSchema);
